// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDja2uGzWPeznnBGDp9GEYrc6qu4M83X5Q',
    appId: '1:309269823883:web:e9c7533dc66ea6eae22f8e',
    messagingSenderId: '309269823883',
    projectId: 'flutter-e5aab',
    authDomain: 'flutter-e5aab.firebaseapp.com',
    storageBucket: 'flutter-e5aab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdWa6aY7TGQD_oDpo9x1g9hcQVBdJF_o',
    appId: '1:309269823883:android:14b70675a5aeb62fe22f8e',
    messagingSenderId: '309269823883',
    projectId: 'flutter-e5aab',
    storageBucket: 'flutter-e5aab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDja2uGzWPeznnBGDp9GEYrc6qu4M83X5Q',
    appId: '1:309269823883:web:771ca656885925dee22f8e',
    messagingSenderId: '309269823883',
    projectId: 'flutter-e5aab',
    authDomain: 'flutter-e5aab.firebaseapp.com',
    storageBucket: 'flutter-e5aab.firebasestorage.app',
  );
}
